import { CampusItem } from '../types';

export const INITIAL_CAMPUS_ITEMS: Omit<CampusItem, 'id' | 'createdAt' | 'updatedAt' | 'flagsCount' | 'isFlagged'>[] = [
  {
    type: 'found',
    title: 'Blue Hydro Flask with Campus Stickers',
    description: 'Found on the 2nd floor silent study area of the Main Library near table 14. Covered in National Park stickers and a CS club badge.',
    category: 'accessories',
    location: 'Main Library - 2nd Floor',
    date: '2026-09-27',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_1',
    userDisplayName: 'Elena Rostova',
    userEmail: 'elena.rostova@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-9921',
    securityQuestion: 'What specific animal sticker is placed near the bottom rim?',
    pickupLocation: 'Main Library Front Circulation Desk',
  },
  {
    type: 'lost',
    title: 'Sony WH-1000XM4 Noise Canceling Headphones',
    description: 'Left in Science Lecture Hall 101 after Organic Chemistry II at 3:30 PM. In a black zipper case with a short USB-C charging cord.',
    category: 'electronics',
    location: 'Science Quad - Hall 101',
    date: '2026-09-26',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_2',
    userDisplayName: 'Marcus Chen',
    userEmail: 'marcus.c@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-4819',
    reward: '$30 Campus Dining Cash',
  },
  {
    type: 'lend',
    title: 'TI-84 Plus CE Graphing Calculator',
    description: 'Have a spare graphing calculator in good condition with fresh batteries. Happy to lend to anyone taking Calc I/II or Stats exams this week.',
    category: 'electronics',
    location: 'Student Union Lounge / North Hall',
    date: '2026-09-28',
    imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_3',
    userDisplayName: 'Sarah Jenkins',
    userEmail: 's.jenkins@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-3320',
    borrowDurationDays: 5,
  },
  {
    type: 'lend',
    title: 'Clean White Chemistry Lab Coat (Size M) + Splash Goggles',
    description: 'Passed Chem Lab last semester! Clean, freshly laundered lab coat and anti-fog safety goggles available for short-term borrow.',
    category: 'lab_equipment',
    location: 'Chemistry Annex / South Campus',
    date: '2026-09-27',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_4',
    userDisplayName: 'Devon Reed',
    userEmail: 'd.reed@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-7741',
    borrowDurationDays: 7,
  },
  {
    type: 'borrow_request',
    title: 'Looking to Borrow: HDMI to USB-C Display Adapter',
    description: 'Need an HDMI to USB-C dongle for a capstone presentation this Thursday afternoon between 1 PM and 4 PM. Will return right after!',
    category: 'electronics',
    location: 'Engineering Hall / Makerspace',
    date: '2026-09-28',
    imageUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_5',
    userDisplayName: 'Priya Patel',
    userEmail: 'priya.p@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-6523',
    borrowDurationDays: 1,
  },
  {
    type: 'found',
    title: 'Student ID Card + Key with Red Lanyard',
    description: 'Found on the bench outside the Campus Recreation & Gym center near the basketball courts. Turned over to front sports desk.',
    category: 'id_cards',
    location: 'Campus Recreation & Gym',
    date: '2026-09-27',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=600&q=80',
    status: 'open',
    userId: 'seed_student_6',
    userDisplayName: 'Jordan Lee',
    userEmail: 'jordan.lee@campus.edu',
    userPhotoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    userCampusId: 'STU-1029',
    securityQuestion: 'What initials or name are on the student card?',
    pickupLocation: 'Recreation Center Front Desk',
  }
];

export const INITIAL_ANNOUNCEMENT = {
  title: 'Campus Lost & Found Notice — Midterm Week',
  message: 'Campus Security desk at Hall 2 is receiving high volume of lost student IDs and keys. Check listings here or stop by between 8 AM and 7 PM.',
  urgency: 'info' as const,
  authorId: 'admin_sys',
  authorName: 'Campus Administration',
  active: true,
};
